<?php
$first = array(
	'job'=>array(
		array(
			'name'=>'律师助理1',
			'school'=>'大专及以上',
			'num'=>'2',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据1)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据1)")
			)
		),
		array(
			'name'=>'律师助理2',
			'school'=>'大专及以上',
			'num'=>'1',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据2)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据2)")
			)
		),
		array(
			'name'=>'律师助理3',
			'school'=>'大专及以上',
			'num'=>'5',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据3)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据3)")
			)
		),
		array(
			'name'=>'律师助理4',
			'school'=>'大专及以上',
			'num'=>'4',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据4)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据4)")
			)
		),
		array(
			'name'=>'律师助理5',
			'school'=>'大专及以上',
			'num'=>'3',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据5)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据5)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据5)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据5)")
			)
		),
		array(
			'name'=>'律师助理6',
			'school'=>'大专及以上',
			'num'=>'8',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据6)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据6)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据6)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据6)")
			)
		)
	),
	"page"=>"3"
);
$second = array(
	'job'=>array(
		array(
			'name'=>'行政助理1',
			'school'=>'大专及以上',
			'num'=>'2',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据1)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据1)")
			)
		),
		array(
			'name'=>'行政助理2',
			'school'=>'大专及以上',
			'num'=>'1',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据2)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据2)")
			)
		),
		array(
			'name'=>'行政助理3',
			'school'=>'大专及以上',
			'num'=>'5',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据3)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据3)")
			)
		),
		array(
			'name'=>'行政助理4',
			'school'=>'大专及以上',
			'num'=>'4',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据4)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据4)")
			)
		),
		array(
			'name'=>'行政助理5',
			'school'=>'大专及以上',
			'num'=>'3',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据5)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据5)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据5)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据5)")
			)
		),
		array(
			'name'=>'行政助理6',
			'school'=>'大专及以上',
			'num'=>'8',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据6)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据6)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据6)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据6)")
			)
		)
	)
);
$third = array(
	'job'=>array(
		array(
			'name'=>'律师1',
			'school'=>'大专及以上',
			'num'=>'2',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据1)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据1)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据1)")
			)
		),
		array(
			'name'=>'律师2',
			'school'=>'大专及以上',
			'num'=>'1',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据2)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据2)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据2)")
			)
		),
		array(
			'name'=>'律师3',
			'school'=>'大专及以上',
			'num'=>'5',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据3)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据3)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据3)")
			)
		),
		array(
			'name'=>'律师4',
			'school'=>'大专及以上',
			'num'=>'4',
			'time'=>'2016-6-20',
			'salary'=>'2000',
			'type'=>'全职',
			'experience'=>'不限',
			'department'=>'商务部',
			"list1"=>array(
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)"),
				array("li"=>"协助律师进行调查、取证、出证工作；(这是模拟数据4)")
			),
			"list2"=>array(
				array("li"=>"本科及以上学历，法学专业优先；(这是模拟数据4)"),
				array("li"=>"良好的沟通能力及团队合作精神；(这是模拟数据4)")
			)
		)
	)
);

$page = $_POST['value'];
if($page == 1){
	echo json_encode($first);
};
if($page == 2){
	echo json_encode($second);
};
if($page == 3){
	echo json_encode($third);
};
?>