<?php
$movie = array(
	'list'=>array(
		array(
			'img'=>'1',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件1'
		),
		array(
			'img'=>'2',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件2'
		),
		array(
			'img'=>'3',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件3'
		),
		array(
			'img'=>'4',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件4'
		),
		array(
			'img'=>'5',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件5'
		),
		array(
			'img'=>'6',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件6'
		),
		array(
			'img'=>'7',
			'instructions'=>'致力于为客户提供专于为客以专业操作知识产权维权批量案件7'
		)
	)
);
echo json_encode($movie);
?>